### ISSUE TITLE
Add vivado projects for hdf files

### ISSUE THREAD

**Issue by FranzForstmayr** [Xilinx/hdf-examples#2]
It would be nice, if the original vivado project is inside for each hdf file, so you'll have an good starting point for own projects. I'm using ZCU111 actually, so i please append it.

**Comment by mharth** [comment]
this is an example on how to pull in the HDF for a Yocto build. Yocto builds does not have dependencies about Vivado project at this point of time.

**Comment by FranzForstmayr** [comment]
The rfdc driver uses xparameters.h files, generated from hdf, isn't it? I have problems getting rfdc driver run, or is there an easier way to configure the RF-PLL on ZCU111?
