### ISSUE TITLE
system.xsa is missing for zybo-zynq7

### ISSUE THREAD

**Issue by Livius90** [Xilinx/hdf-examples#4]
Hi!
For Digilent Zybo boards (machine zybo-zynq7 and zybo-linux-bd-zynq7) Xilinx Yocto manifest is unable to build because system.xsa is missing in Xilinx hdf-examples repo. Can you fix these files to able to build it for Digilent board?

**Comment by ckalluri73** [comment]
Hi,

As of today we don't have any example xsa for Digilent zybo boards. If you have an example xsa created against the 2020.1 manifest, I can include the xsa to this repo to prevent future failures. 

Thanks,
Chandana

**Comment by Livius90** [comment]
If you do not care about to support Zybo boards, please remove it from your meta layer's [supported boards/machines list](https://github.com/Xilinx/meta-xilinx/blob/rel-v2021.2/meta-xilinx-bsp/README.md#supported-boardsmachines).
